### PR TITLE
unnecessary_this on field initializers

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
BTW I wonder when `this` is required in field initializer... Never ?

**Comment by bwilkerson** [comment]
> I wonder when this is required in field initializer... Never ?

Yes, never. The spec says that an initializer of the form `x = e` is equivalent to `this.x = e`.

**Comment by a14n** [comment]
It's not a breaking change: it's a fix of a bug regarding the effective dart rule [DON’T use `this.` when not needed to avoid shadowing](https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-this-when-not-needed-to-avoid-shadowing) :) There's even an example with that case!

**Comment by a14n** [comment]
>Yes, never. The spec says that an initializer of the form x = e is equivalent to this.x = e.

Thanks! Good to know.

**Comment by bwilkerson** [comment]
> There's even an example with that case!

Ah, I didn't realize that. (It's been a long time since I read the guide. :-)

**Pull request merged**
