### PR TITLE
Fix use_build_context_synchronously in if conditions

### PR DESCRIPTION
**Pull request by kuhnroyal**
# Description

Prevent false positives in IF statements, only check the IF statements.

Fixes false positives introduced in https://github.com/dart-lang/linter/pull/3458

### CODE REVIEW

**Comment by pq** [comment]
@a14n: would you mind taking a look?

**Review by a14n — APPROVED** [review]
LGTM

**Review by pq — APPROVED** [review]

**Comment by pq** [comment]
@kuhnroyal: could you add yourself to [`AUTHORS`](https://github.com/dart-lang/linter/blob/main/AUTHORS), while you're at it?

Thanks for the contribution!

**Review by pq — CHANGES_REQUESTED** [review]
(Hold for AUTHORS update.)

**Comment by kuhnroyal** [comment]
@pq Done, and also fixed the typo in the commit message

**Comment by pq** [comment]
The build failures will clear up w/ a rebase so I'll go ahead and merge as is.  Thanks for the contribution!

**Comment by kuhnroyal** [comment]
Is there any way this change can be made available in the next Dart/Flutter Patch (2.19.1/3.7.1)?

**Pull request merged**
