### PR TITLE
remove third party package special-casing from `directives_ordering`

### PR DESCRIPTION
**Pull request by pq**
See: https://github.com/dart-lang/site-www/issues/2402

/cc @munificent @kwalrath @bwilkerson

### CODE REVIEW

**Comment by pq** [comment]
@kwalrath,  @munificent: is the corresponding work in dart-lang/site-www#2402 done and landed?  If so, could you look at the updated docs here to spot check?

Thanks!

**Comment by munificent** [comment]
Is the doc change here just removing that section from directives_ordering.dart? If so, LGTM.

**Comment by kwalrath** [comment]
> @kwalrath, @munificent: is the corresponding work in [dart-lang/site-www#2402](https://github.com/dart-lang/site-www/issues/2402) done and landed? If so, could you look at the updated docs here to spot check?

Yes, https://github.com/dart-lang/site-www/issues/2402 was fixed by https://github.com/dart-lang/site-www/pull/2405, which went live automagically after that PR was merged (3+ weeks ago).

**Comment by pq** [comment]
Thanks!

@bwilkerson: could you PTAL at the  source changes?

**Pull request merged**
