### PR TITLE
Add --strong flag to use strong-mode analyzer

### PR DESCRIPTION
**Pull request by ochafik**

### CODE REVIEW

**Comment by alexeieleusis** [comment]
I think removing the merge commit and instead rebasing your branch on top of dart-lang/master will result in a cleaner repo history.

I didn't know the analyzer was not running in strong mode, this is great!

**Comment by ochafik** [comment]
(Rebased)

**Comment by pq** [comment]
Sorry for the slow review.  Looks great.  Thanks 👍

**Comment by ochafik** [comment]
Thanks!

**Pull request merged**
