### PR TITLE
use_build_context_synchronously: handling of await in if conditions

### LINKED ISSUE #3457: use_build_context_synchronously not working with IF
No warning occurs in such case:
```dart
if (await func1(context)) func2(context);
```
When changed to the following:
```dart
  var r = (await func1(context);
  if (r) func2(context);
```
warning is shown.

### PR DESCRIPTION
**Pull request by a14n**
# Description

Warn on `if (await condition) func2(context);`

Fixes #3457

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]

**Review by pq — APPROVED** [review]

**Comment by pq** [comment]
@a14n: do you know if this will catch any new violations on the flutter build bots?

**Comment by a14n** [comment]
> @a14n: do you know if this will catch any new violations on the flutter build bots?

I found at least 2 new diagnostics I'm going to fix

**Comment by a14n** [comment]
Flutter is now ready for the roll as https://github.com/flutter/flutter/pull/106057 is merged.

**Comment by pq** [comment]
Awesome. Thanks!

**Comment by kuhnroyal** [comment]
I think I have false positives with this on:

```dart
if (await condition(context)) print('foo');
```

**Comment by kuhnroyal** [comment]
I created a PR with a fix for the false positives, please check if this makes sense.

**Pull request merged**
