### PR TITLE
Add effective_dart to linter page

### PR DESCRIPTION
**Pull request by tenhobi**
# Description

This PR adds effective dart badge to lints, similarly to pedantic and flutter. (Discussed in https://github.com/dart-lang/linter/pull/1781)

I tested to build pages on local, and everything works as expected (except I don't have styles and images – mentioned bellow).

# Issues

I do not know where to save the badge for the effective dart. In `tools/doc.dart:174` there is mentioned `effective_dart`, which is just a copy from pedantic, but I do not know where it is stored.

I would like to use this [badge](https://github.com/tenhobi/effective_dart/#badge) (https://img.shields.io/badge/style-effective_dart-40c4ff.svg).

cc @pq

### CODE REVIEW

**Comment by tenhobi** [comment]
I have investigated this further how it was in the pedantic badge PR done. There is also no svg uploaded, so I can assume you upload it manually to a server?

I assume you will also upload an effective dart badge [](), right?

**Comment by tenhobi** [comment]
@pq hi, thanks for a response. Maybe I am not expressing myself properly.

These (already existing) badges

image

are referenced in code as from local source. When I inspect the website, for example, the pedantic badge's image is from the source at http://dart-lang.github.io/linter/lints/style-pedantic.svg.

Therefore,

- I do not know where they are stored (in the repo or are they from another one?)
- I do not know how to properly finish this PR = where to place the badge for effective dart
- Also, if you can tell me the proper way to build the website, that would be nice, because I can only build HTML without styles, images, etc.

**Comment by tenhobi** [comment]
Oh, I must have been blind. The files are in https://github.com/dart-lang/linter/tree/gh-pages/lints. Sorry for the confusion.

Should I upload the svg to the gh-pages branch in separate PR?

**Comment by pq** [comment]
Aha.  I actually didn't realize the SVGs were there either so we were both confused.  Sorry about that!

The PR flow for the gh-pages branch is funny so I just went ahead and uploaded it.

https://github.com/dart-lang/linter/blob/gh-pages/lints/style-effective_dart.svg

If you're good with me merging this change, I'll land your work and publish the docs.

**Comment by tenhobi** [comment]
Thanks, you can merge! 💙

**Comment by pq** [comment]
Thanks so much for this contribution!

FWIW, this is nudging me to get doc gen into the build (https://github.com/dart-lang/linter/issues/1806).  Something I've been thinking we should do for a while. Thanks for that too!

**Comment by pq** [comment]
.... and we're live:

image


http://dart-lang.github.io/linter/lints/

**Comment by tenhobi** [comment]
Awesome, that looks fantastic! Thx again. 💎

**Comment by pq** [comment]
I agree.  Thanks for making it happen!

**Pull request merged**
