### PR TITLE
Add `no_logic_in_state_constructor`

### PR DESCRIPTION
**Pull request by minhqdao**
The constructor of a `State` object is not supposed to contain any logic. That logic should go into `State.initState()`.

Closes https://github.com/dart-lang/linter/issues/3059.

### CODE REVIEW

**Comment by srawlins** [comment]
Apologies on the delayed review, but we should resolve the discussion at https://github.com/dart-lang/linter/issues/3059 before landing an implementation.

**Comment by srawlins** [comment]
I'll convert this to a draft PR until the discussion is resolved.

**Comment by minhqdao** [comment]
> Apologies on the delayed review, but we should resolve the discussion at #3059 before landing an implementation.

No worries. I just thought in the beginning that this was going to be very straightforward and wouldn't require much discussion.

**Comment by devoncarew** [comment]
Thanks for the contribution! The code for the linter has since moved into the sdk repo (at https://github.com/dart-lang/sdk/tree/main/pkg/linter). If you think this PR is still relevant, consider re-creating it against the source there (see https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md).

**Pull request closed without merging**
