### PR TITLE
Fix rule: omit_local_variable_types

### PR DESCRIPTION
**Pull request by JPaulsen**
Fixes https://github.com/dart-lang/sdk/issues/29384

### CODE REVIEW

**Comment by JPaulsen** [comment]
@bwilkerson I know this is the bug and this fixes it but I do not know how to reproduce it, I need a ForEachStatement that has an Iterable with an empty typeArgument

**Comment by JPaulsen** [comment]
If I do this:
```dart
void foo() {
  final array = [];
  for (a in array) {
  }
}
```

the variable array is a variable with 1 typeArgument that is dynamic :S so I have not been able to understand what happened and how to reproduce the bug.

**Comment by bwilkerson** [comment]
Perhaps something like this?
```
void printItems(Iterable items) {
  for (var item in items) {
    print(item);
  }
}
```

**Comment by bwilkerson** [comment]
I agree, it is strange. I would have expected that the type would always have a type argument. Do we know that the type is "Iterable"? What if the type is not generic, something like:
```
void printItems(String items) {
  for (var item in items) {
    print(item);
  }
}
```
Perhaps then the type arguments is an empty list because `String` has no type parameters.

**Comment by JPaulsen** [comment]
@bwilkerson in this case I got an error that says ERROR: The type 'String' used in the 'for' loop must implement Iterable. ([linter] test/rules/omit_local_variable_types.dart:14)

**Comment by JPaulsen** [comment]
I also found other bug, if you reuse a variable in a foreach (it was already declared) then loopVariable is null, so I also added that and created a test

**Comment by bwilkerson** [comment]
Maybe something like this?
```
abstract class StringIterator implements Iterator<String> {}
void printItems(StringIterator items) {
  for (var item in items) {
    print(item);
  }
}
```

**Comment by JPaulsen** [comment]
It was that!!!, I fixed and could lint this case :D

**Pull request merged**
