### PR TITLE
Doc: Fix grammatical error the/than

### PR DESCRIPTION
**Pull request by manuelF**
Fix small grammar error in no_duplicate_case lint.

### CODE REVIEW

**Comment by pq** [comment]
Thanks!

**Comment by pq** [comment]
@manuelF : I'd like to add an attribution in the `AUTHORS` file.  What's a good email for you?

Thanks in advance!

**Comment by manuelF** [comment]
I prefer mferreria at Google. Thanks!

**Comment by pq** [comment]
Ah!  In that case, we've got you covered under the 

    Google Inc. <*@google.com>

entry.

Thanks again for the contribution!

**Pull request merged**
