### PR TITLE
A basic Code of Conduct.

### PR DESCRIPTION
**Pull request by pq**
Following the lead of other inclusive OSS projects (and the advice of [github](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/), a simple [code of conduct](https://opensource.guide/code-of-conduct/)).

@bwilkerson 

cc: @devoncarew @kevmoo

### CODE REVIEW

**Comment by pq** [comment]
Ping! 😄

**Comment by bwilkerson** [comment]
While I certainly don't have any problem with the content of the file, I don't see anything like this on the other packages developed by the Dart team. Kind of seems like the kind of thing that ought to be consistently applied (or not) across our product.

@anders-sandholm Any thoughts / direction?

**Comment by kevmoo** [comment]
Let's have a discussion about this as a team and make a call.

**Comment by bwilkerson** [comment]
Yep, that's why I asked Anders to look at this.

**Comment by pq** [comment]
SGTM. 👍 

@anders-sandholm : I'd be curious to hear what you all think.

**Comment by anders-sandholm** [comment]
We discussed this. 
Would definitely make sense to have a code of conduct.
While I think we could land this here, it may make more sense to include a similar file in the main repo (SDK) and the standard template repo so it is automatically included in new repos going forward.

**Comment by pq** [comment]
Fantastic.  Thanks @anders-sandholm!

Is there an issue I can track on the SDK?  Or should I create one?

**Comment by anders-sandholm** [comment]
Not yet. 
Feel free to create one.

**Comment by pq** [comment]
Thanks @anders-sandholm !  

Closing in favor syncing up with one in the Dart SDK once it lands (https://github.com/dart-lang/sdk/issues/30051).

**Pull request closed without merging**
