### PR TITLE
[WIP] add tests for optional new/const

### PR DESCRIPTION
**Pull request by a14n**
Related to #995 and #1008

### CODE REVIEW

**Comment by a14n** [comment]
Before merging those additionnal tests need to enable [`previewDart2` in DriverOptions](https://github.com/dart-lang/sdk/blob/4ebdb31646c15b896449b039dd3d517547ac9b1a/pkg/analyzer/lib/src/lint/analysis.dart#L88) and upgrade the analyzer dependency to include https://github.com/dart-lang/sdk/commit/b343d0a80d3e8241345945c49692703c82101894.

BTW: it looks like `--preview-dart-2` is now the default in VM. Shouldn't it be also switched in DriverOptions ?

**Comment by bwilkerson** [comment]
Yes, the VM is now Dart 2 by default (on bleeding edge), so we should update the linter package before it is next pulled into the SDK. That would include `DriverOptions` and `pubspec.yaml` changes.

If we need a new version of the analyzer, then as far as I know we can publish one.

**Comment by pq** [comment]
Thanks @bwilkerson! The rub is that `DriverOptions` lives in `analyzer`.  Maybe we can take a look at this together later today?

**Comment by bwilkerson** [comment]
Yep. Let's talk with @devoncarew when you get in (the answer might depend on when we decide to stop supporting `--no-preview-dart-2` in the analyzer).

**Comment by pq** [comment]
@a14n :

> Before merging those additionnal tests need to enable previewDart2 in DriverOptions 

https://github.com/dart-lang/linter/pull/1039 should do this in the tests themselves.

> and upgrade the analyzer dependency to include dart-lang/sdk@b343d0a.

I tried this locally and still saw breaks in `prefer_const_constructors`; is that expected?

**Comment by a14n** [comment]
>I tried this locally and still saw breaks in `prefer_const_constructors`; is that expected?

No. I need to have a look (but perhaps tomorrow).

**Comment by pq** [comment]
Cool.  Thanks @a14n !

**Comment by a14n** [comment]
To make the tests pass you need to override the analyzer package to use the one from the SDK

```diff
diff --git a/pubspec.yaml b/pubspec.yaml
index 469168d..8e1eed3 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -20,3 +20,10 @@ dev_dependencies:
   matcher: ^0.12.0
   path: '>=0.9.0 <2.0.0'
   test: ^1.0.0
+dependency_overrides:
+  analyzer:
+    path: ../sdk/pkg/analyzer
+  front_end:
+    path: ../sdk/pkg/front_end
+  kernel:
+    path: ../sdk/pkg/kernel
```

**Comment by pq** [comment]
@a14n: I thought I'd tried that, sorry!

Should that fix  #1040 as well?

**Comment by pq** [comment]
In any event, since tests are already failing, shouldn't we go ahead and land this change?

**Comment by a14n** [comment]
The fix is to publish a new analyzer package.

>In any event, since tests are already failing, shouldn't we go ahead and land this change?

I think it's fine.

**Comment by pq** [comment]
Great.  Thanks.  We can follow-up on #1040.

/cc @bwilkerson as we'll want to do an analyzer roll.

**Pull request merged**
