### PR TITLE
support for class decls, enums and mixins

### PR DESCRIPTION
**Pull request by pq**
/cc @bwilkerson

### CODE REVIEW

**Comment by pq** [comment]
Ha!  I just came to the same conclusion. 😄 

I got this rule confused w/ `public_member_api_docs`.

Thanks!

**Comment by pq** [comment]
> There's still a change needed for members in extensions in that the definition of isPrivate needs to change for them.

On closer look, I don't even think we need to change this since it's just checking the `SimpleIdentifier` and not (as maybe it should) take the parent's visibility into consideration. 🤔

**Comment by bwilkerson** [comment]
Yeah, even with classes, a non-private method in a private class probably shouldn't be getting flagged. That said, if no one is complaining, then it might not be important enough to spend time fixing it. Still, it wouldn't hurt to open an issue; we might get user feedback to give us more information.

**Comment by pq** [comment]
https://github.com/dart-lang/linter/issues/1689. 👍

**Pull request closed without merging**
