### PR TITLE
Clarify how the dependencies should be sorted when using `sort_pub_dependencies`

### PR DESCRIPTION
**Pull request by nilsreichardt**
# Description

Clarifies a bit what "Sort dependencies" means. When I read about the linter, was this not clear to me what "Sort dependencies" acutely means.

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]

**Comment by pq** [comment]
Thanks so much for the contribution!

@nilsreichardt: could you follow-up with a PR to add yourself to `AUTHORS`?

(I'll take a look at the main bot failure...)

**Review by pq — APPROVED** [review]

**Comment by nilsreichardt** [comment]
@pq Opened #3556 👍

Should I also update my changes to [dart-lang/site-www](https://github.com/dart-lang/site-www)? Or is this synced automatically?

https://github.com/dart-lang/site-www/blob/d6a056d7f6840b391c3c8cd3e916cc6cdb3a1756/src/_data/linter_rules.json#L415

**Comment by pq** [comment]
Thanks!

@parlough: can speak to how the site-www syncing works -- last I recall it was done manually on new linter releases (but not _by us_...)

In fact, @parlough: let's capture this somewhere.  (Maybe in https://github.com/dart-lang/linter/blob/main/doc/RELEASING.md? <-- aside: oof, that's out of date...)

**Comment by parlough** [comment]
Currently, I manually update it from the (now automatically) generated [machine.json](https://github.com/dart-lang/linter/blob/gh-pages/lints/machine/rules.json) as shown in https://github.com/dart-lang/site-www/pull/4156, where I directly copy it to [linter_rules.json](https://github.com/dart-lang/site-www/blob/main/src/_data/linter_rules.json). 

I am mostly unavailable for the next few weeks, but mid-late August, I hope to automate this and diagnostic message updates.

**Comment by pq** [comment]
Thanks @parlough!

**Pull request merged**
