### PR TITLE
Allow public const field declarations with omitted type

### LINKED ISSUE #1121: type_annotate_public_apis reports missing type for static const
Consider [the following class member declaration](https://github.com/dart-lang/site-www/blob/78ce4759d1102ad4d96cc392e89874fa72df4404/examples/misc/lib/language_tour/classes/misc.dart#L21-L25): 

```dart
class Queue {
  static const initialCapacity = 16;
}
```

The `type_annotate_public_apis` lint causes this issue to be reported:

```nocode
lint • Type annotate public APIs at lib/language_tour/classes/misc.dart:22:16 • type_annotate_public_apis
```

Being a `static const`, its type is fully determined at compile time from the initializer, so a type annotation would be redundant, and certainly should not be _required_ -- as the lint message seems to suggest.

Of course, such a static const w/o an explicit type annotation can end up having type `dynamic`, which might not be desirable, but that is another issue addressed via the `--no-implicit-dynamic` flag IMHO.

cc @munificent @kwalrath @kevmoo

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #1121

### CODE REVIEW

**Comment by bwilkerson** [comment]
This rule was created to support the Flutter style, so I think we should get Ian's input before changing it. Unfortunately, I can't seem to reference him from this project.

**Comment by a14n** [comment]
I think you mix up with `always_specify_types`. `type_annotate_public_apis` was created to enforce a rule from Effective Dart .

**Comment by bwilkerson** [comment]
That seems likely.

So, has the rule from Effective Dart been updated since this rule was written?

**Comment by pq** [comment]
> This rule was created to support the Flutter style, so I think we should get Ian's input before changing it. 

cc @Hixie

**Comment by Hixie** [comment]
I don't think Flutter would use this. I don't understand why we would want to omit the type in a static const declaration or any declaration. The type is part of what makes the code self-documenting.

**Comment by pq** [comment]
Thanks @Hixie!

@srawlins: it sounds like this would render the rule _less_ useful for Flutter so I think we should reconsider the change.  Thoughts?

**Comment by srawlins** [comment]
You missed a few comments, @pq. Flutter never requested this lint; it came from Effective Dart, but the backing recommendation was accidentally removed. Nothing to do with Flutter.

**Comment by bwilkerson** [comment]
So I'll ask the question again. Has Effective Dart been (or do we know that it will be) re-written to have this exception? If the rule is supposed to support the style guide, then I don't think we should make it behave differently.

**Comment by srawlins** [comment]
@bwilkerson No, Bob's issue, https://github.com/dart-lang/site-www/issues/996, is still open.

**Comment by mit-mit** [comment]
Hi @srawlins is this still being worked on? Can we close it?

**Comment by srawlins** [comment]
Lol the issue that this fixes has been fixed.

**Pull request closed without merging**
