### PR TITLE
add count badge

### PR DESCRIPTION
**Pull request by pq**
image

/cc @bwilkerson

### CODE REVIEW

**Comment by pq** [comment]
@a14n : right.  That's the number of documented lints (http://dart-lang.github.io/linter/lints/) but maybe that's not the best number?

**Comment by pq** [comment]
Either way maybe "lints" is ambiguous as a label?

**Comment by a14n** [comment]
Looking at the badge I expected to have the number of lints activated for the project.

**Comment by pq** [comment]
> Looking at the badge I expected to have the number of lints activated for the project.

Aha!  That's another badge I should make. 👍 

This is just a lint count (vanity I know) and a convenient place to hang a link to http://dart-lang.github.io/linter/lints/.  Can you think of another label that would be more clear?

**Comment by a14n** [comment]
>This is just a lint count (vanity I know)

Ahhh ok. I misunderstood what it was.

>Can you think of another label that would be more clear?

Unfortunately no :-(

**Comment by pq** [comment]
Thanks for the feedback @a14n!  I'm going to work on some other badges and will loop you in when there's something to discuss.

**Pull request merged**
