### PR TITLE
enable some nullsafety lints

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by pq** [comment]
Cool!  I've got a mega PR about to go out that includes these changes (though not the lint enablements but I can add them 👍 ).  Sorry for the duplicated work...  Maybe it's time we setup an announce list or a discourse channel so we can all better coordinate?

**Comment by pq** [comment]
See also: #2453

**Comment by a14n** [comment]
No worries :)

**Comment by bwilkerson** [comment]
> ... though not the lint enablements but I can add them ...

Bonus points if you separate out the lint enablement and, when we enable the lints we ensure that we have bulk fix support for fixing all the violations.

**Pull request closed without merging**
