### PR TITLE
add rule use_null_aware_access

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by zoechi** [comment]
Doesn't the analyzer produce a warning for this already?
I saw them freqiently for such code. 
Something like "... could be Null ..." (have to check - just on the phone now)
Perhaps it doesn't cover all cases?

**Comment by zoechi** [comment]
image

**Comment by a14n** [comment]
humm, strange, I never saw this warning. Do you have something special about your config ?

**Comment by a14n** [comment]
My bad. I made my tests in a folder that was excluded from analysis :-/

Thanks to notice it.

I will extend the actual rule in sdk to cover all the cases I point out in the tests.

**Pull request closed without merging**
