### PR TITLE
Example config update and doc tweaks.

### PR DESCRIPTION
**Pull request by pq**
@bwilkerson @filiph

### CODE REVIEW

**Comment by pq** [comment]
Thanks!

**Comment by alexeieleusis** [comment]
This is a bit late but, should we also add a config file for the Effective Dart rules? Similarly we have enough performance/correctness rules that might also make it worth having them in its own file/section.

**Comment by alexeieleusis** [comment]
I can do it later since definitely is not an urgent thing.

**Comment by pq** [comment]
@alexeieleusis 👍  yes please, do add an example file that aggregates the effective dart rules.  Thanks!

**Comment by pq** [comment]
(Happy to push out a quick `0.1.32` when you do as well.)

**Pull request merged**
