### PR TITLE
Fix false positive in `test_types_in_equals`

### LINKED ISSUE #443: test_types_in_equals false positive
```dart
bool operator ==(Object other) {
    if (other is! Foo) return false;
   ...
}
```

### PR DESCRIPTION
**Pull request by asashour**
Fixes #443

### CODE REVIEW

**Comment by bwilkerson** [comment]
I'm tempted to just close the issue without applying this PR. That issue was opened before null safety was enabled, and I don't think the same implementation pattern applies now. For example, I think the test case you added would be better written as
```
class Good2 {
  bool b = false;

  @override
  bool operator ==(Object other) {
    if (other is! Good2) return false;
    return b == other.b;
  }

  @override
  int get hashCode => b.hashCode;
}
```

Because type promotion is so much better than it used to be I don't think there are many (if any) reasons to use `as` in an `==` method. Hence, I don't think the rule needs to accept this case anymore.

**Comment by asashour** [comment]
With null-safety, there is a `lint` unnecessary cast in 

    Good2 otherGood = other as Good2;

I am fine with closing the issue, with giving a reason.

**Comment by pq** [comment]
> Because type promotion is so much better than it used to be I don't think there are many (if any) reasons to use as in an == method. Hence, I don't think the rule needs to accept this case anymore.

👍   I tend to agree.

**Comment by asashour** [comment]
The lint is already not accepting `as` an `==` method, closing the PR.

**Pull request closed without merging**
