### PR TITLE
Expanding lint writing documentation

### PR DESCRIPTION
**Pull request by nscobie**
# Description

Working with the linter has been a lot of fun! However, there were some areas I struggled with due to a lack of documentation, especially with respect to available tooling.

This proposed documentation expansion focuses on `doc/WritingLints.MD`, and mostly comes from trying to distill what I learned by reading through the code and collecting some previously disparate knowledge. How exactly this information should be further edited/distilled/integrated is totally up to you all, but I hope some of it might be useful to other public contributors rather than languishing in a private document of mine. 😄 

I moved some existing content around to hopefully flow better with the new structure, but I don't believe I outright deleted any existing content. However, the textual diff is a bit messy, so visually comparing the rendered Markdown might be easier.

- [New WritingLints.MD](https://github.com/dart-lang/linter/blob/a55f4291b771610faf200ce1c116904742cfe31b/doc/WritingLints.MD)
- [Previous WritingLints.MD](https://github.com/dart-lang/linter/blob/05ab71a36a2b07e488b757d31b036aadd34632a2/doc/WritingLints.MD) (commit [05ab71a](https://github.com/dart-lang/linter/commit/05ab71a36a2b07e488b757d31b036aadd34632a2))

### CODE REVIEW

**Comment by pq** [comment]
Awesome!  I'll take a look tomorrow but I've added Brian as well since he's a goto for a lot of the mechanics.

**Comment by nscobie** [comment]
@bwilkerson Glad to hear!

I agree with your suggestions, I think they definitely help with clarity. No need to worry about giving offense, the only thing you should be worried about is that now I have adopted your pet peeves. :-)

Unrelated: I have a known issue of being too verbose, so let me know if anyone has suggestions for where things should be trimmed down or rephrased.

**Comment by srawlins** [comment]
Sorry this has fallen off the radar. If you'd still like to land, can you fix merge conflicts, and we can try again to review? Sorry again!

**Comment by bwilkerson** [comment]
If the OP can't do so, I think that we should. Please don't close this without pinging me first.

**Comment by pq** [comment]
No worries, thanks @nscobie!

**Comment by parlough** [comment]
Yeah this is really amazing, but it seems like a lot covered here has already changed (especially tests) and will continue to change with the move to the SDK. Would be nice to codify something like this and the documentation decisions in the future.

**Pull request closed without merging**
