### PR TITLE
rename score.yaml to core.yaml

### PR DESCRIPTION
**Pull request by devoncarew**
- rename `score.yaml` to `core.yaml`

@pq

### CODE REVIEW

**Comment by pq** [comment]
I like this!

@munificent @mit-mit : how do you feel about generally renaming the "score" set to "core"?

**Comment by devoncarew** [comment]
Before this rename, it wasn't immediately obvious to me the relationship between the 'score' lints and the 'recommended' lints.

**Comment by mit-mit** [comment]
SGTM

**Review by pq — APPROVED** [review]
👍

**Comment by munificent** [comment]
I don't have a super strong opinion, but for what it's worth, I slightly prefer "score" because then the name clearly states what it means. "Core" is pretty vague.

**Pull request merged**
