### PR TITLE
Rule name cleanup (pre-publish).

### PR DESCRIPTION
**Pull request by pq**
Some rule name cleanup to stay (more) consistent with existing rules.

@bwilkerson 

FYI @alexeieleusis @JPaulsen

### CODE REVIEW

**Comment by Hixie** [comment]
@pq Were these rule changes announced anywhere?

**Comment by pq** [comment]
@Hixie the hope is that these were renamed before anyone got to using them but in general we should have a process in place (a la the conversation around Flutter breaking changes).  Maybe we should create a linter-announce alias for this kind of thing (and generally for releases)?

**Comment by Hixie** [comment]
We use at least one of them! :-) (unnecessary_brace_in_string_interp)

I don't mind if they're not announced or anything. I just want to make sure we keep up to date. I'm not sure I would have noticed except that I happened to be crawling in the list and was lucky.

My ideal scenario would be for there to be a way to run an .analysis_options file through some script and have it tell me all the lints that are omitted and all the listed lints that are unknown (errors), ideally with a way for it to skip omitted lints that are present but commented out or some such. Basically I want to make sure that we aren't using bogus lint names and that we have made an explicit decision on every lint that does exist.

**Comment by pq** [comment]
Thanks @Hixie (and mea culpa!)  I agree that some kind of validation support would be great and as it happens I added some rudimentary support to the server a while back but it never made it into the CLI.   I'll fix that soon though:

https://github.com/dart-lang/sdk/issues/29317

Cheers!

**Pull request merged**
