### PR TITLE
Fix false positive in `comment_references`

### LINKED ISSUE #574: comment references: false positive on Markdown links
http://dart-lang.github.io/linter/lints/comment_references.html

The `[rfc]` bits reference the inline-URL, but come up as

`INFO: Only reference in scope identifiers in doc comments. ([crypto] lib/src/sha256.dart:15)`

```dart
/// An instance of [Sha256].
///
/// This instance provides convenient access to the [Sha256][rfc] hash function.
///
/// [rfc]: http://tools.ietf.org/html/rfc6234
final sha256 = new Sha256._();
```

### PR DESCRIPTION
**Pull request by asashour**
Fixes #574

This is based on the following assumptions:

1. `visitComment()` is always called before its corresponding `visitCommentReference()`
2. The second part of the [Reference-style Links](https://www.markdownguide.org/basic-syntax/#reference-style-links) is defined within the same comment as the first part, and not at the dart file level

### CODE REVIEW

**Review by bwilkerson — COMMENTED** [review]
I would approve this except for the fact that it will close the issue but doesn't contain a test for the `[label][]` case. It might already work, but it would be good to prevent regressions if that's the case.

If it doesn't work it's fine to merge this as is, but I wouldn't want to close the issue.

**Comment by asashour** [comment]
Sure, we don't want to merge incomplete things, unless it is agreed, and it doesn't close the original ticket.

Honestly, I didn't find a case of `[label][]` in Markdown specs, however all possible (possibly incorrect) cases were added.

We may later go into valid/invalid cases and trigger lints, but I guess this should be another issue.

**Comment by bwilkerson** [comment]
I'm not sure which specs you're referring to, but it is documented in at least one place https://daringfireball.net/projects/markdown/syntax#link (search for "implicit link name").

**Comment by asashour** [comment]
Thanks for hinting. I put the link in the PR description, which points to the Markdown basic syntax, but is somewhat different. https://www.markdownguide.org/basic-syntax/#reference-style-links

Test cases were updated.

**Review by bwilkerson — APPROVED** [review]
Thanks.

The `dartdoc` tool uses the [markdown package](https://pub.dev/packages/markdown) to parse markdown, and it includes some extensions, including those in the link I sent you, which were part of the Perl Markdown set. I think this lint should correctly handle the same markdown as is supported by that package.

**Comment by pq** [comment]
@jcollins-g: I don't know if you have enough context but wonder if you'd take a quick look at the assumptions made here.  This feels like a step in the right direction but it'd be great to hear you confirm that?  Thanks!

**Comment by jcollins-g** [comment]
> @jcollins-g: I don't know if you have enough context but wonder if you'd take a quick look at the assumptions made here. This feels like a step in the right direction but it'd be great to hear you confirm that? Thanks!

Yep, I saw @bwilkerson 's comment and it seemed correct to me.  The link types mentioned are all supported by dartdoc's markdown AFAIK.

**Comment by pq** [comment]
Super, thanks!

**Comment by srawlins** [comment]
I think this is good to merge then. Merge with main?

**Comment by pq** [comment]
Yep.  Looks like we've got a merge conflict but then I think we're good to go.

Thanks for the patience @asashour!

**Review by pq — APPROVED** [review]
👍

**Pull request merged**
