### PR TITLE
For loops are not required to have a condition (sdk issue 32588)

### PR DESCRIPTION
**Pull request by bwilkerson**

### CODE REVIEW

**Comment by bwilkerson** [comment]
Is there a way to get Travis to re-run? I believe that the failures above were caused by a different merge and should now be fixed.

**Comment by pq** [comment]
When you click the build, do you see these options in the top right?

image

image

If not, you may not be logged in...  I kicked them for you FWIW

**Comment by a14n** [comment]
@bwilkerson you can rebase your commit on top of master and push it again (rebase creates an other commit and triggers a new build when pushed)

**Comment by pq** [comment]
FWIW: I have no idea why the CLAs are now borked (or how to un-bork them short of going nuclear with a fresh PR).

**Comment by bwilkerson** [comment]
I managed to mess something up, so I'm closing this in favor of https://github.com/dart-lang/linter/pull/931.

**Pull request closed without merging**
