### PR TITLE
Change missing_whitespace_between_adjacent_strings to use SimpleAstVisitor

### PR DESCRIPTION
**Pull request by DanTup**
Noted in discussions at https://github.com/dart-lang/linter/pull/3080#discussion_r761283802.

@bwilkerson

### CODE REVIEW

**Comment by pq** [comment]
Great catch!

**Review by bwilkerson — APPROVED** [review]
Thanks!

**Comment by pq** [comment]
It's interesting to take note of the payoff.  While imprecise, the benchmarking bot suggests you just scored a big win.

```
-----------------------------------------------------------------------------
Timings                                                                    ms
-----------------------------------------------------------------------------

missing_whitespace_between_adjacent_strings                                23  (BEFORE 😬)

missing_whitespace_between_adjacent_strings                                 6  (AFTER 🏅)
```

Thanks a million Danny!

🍻

**Comment by DanTup** [comment]
Nice :-) The find was a bit of a fluke (and thanks to @bwilkerson - I almost added a similar perf hit in my other PR 😁)

Cool idea having the perf measured so easily in the PR bot output like that :-)

**Pull request merged**
