### PR TITLE
Fix code that is now triggering lints

### PR DESCRIPTION
**Pull request by bwilkerson**
Just some code cleanup.

### CODE REVIEW

**Comment by pq** [comment]
As discussed in person, we should wait to land this until `2.2.0-dev.1` is available to travis.

In the meantime, we could consider disabling `prefer_collection_literals`...  Alternatively we could all just patch in these changes locally.  No big opinion here. 🤷‍♂️

**Comment by pq** [comment]
I think we can land this one now. 👍

**Comment by pq** [comment]
Aside: the coverage report is curious... 🤔

**Comment by bwilkerson** [comment]
Agreed. I don't know why the coverage would have dropped. Perhaps whatever we're using to measure it doesn't understand set literals and hence isn't able to compute coverage correctly?

**Pull request merged**
