### PR TITLE
bad examples in list_remove_unrelated_type

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by pq** [comment]
@a14n: is this ready to review?

When it is, perhaps @alexeieleusis can take a look?

**Comment by a14n** [comment]
It is ready for review.

**Comment by pq** [comment]
Super!

@alexeieleusis : this one is your bailiwick so maybe take a look?

Thanks!

**Comment by alexeieleusis** [comment]
Thank you @a14n!

**Pull request merged**
