### PR TITLE
Add package:effective_dart

### PR DESCRIPTION
**Pull request by tenhobi**
Hello,

I have updated the effective dart lint rules I previously added to this repository and replaced it by the `packages:effective_dart`, which covers those updates and can be included in projects in way as `package:pedantic` can be.

This will make updating the list easier and we can make versions etc.

Thanks, 
let me know if there is any trouble. 👍

### CODE REVIEW

**Comment by tenhobi** [comment]
Travis fails for some reason tho. It seems it drop maintenance to 90 from 100 for some reason?

**Comment by pq** [comment]
I'm not able to get anything from travis at all... Looks like they're possibly having infrastructure issues?

Can you paste the end of the failed build here and I can look at it?  (Assuming you have it...)

**Comment by pq** [comment]
https://travis-ci.org/dart-lang/linter/builds/601269524?utm_source=github_status&utm_medium=notification

**Comment by tenhobi** [comment]
@pq 
image

**Comment by pq** [comment]
Hmmm.  Running the baseline locally fails for me too which (w/o your change) as it looks like we've got a dependency to upgrade.  I'll have a fix for that in a sec.

FWIW, here's what we're running:

https://github.com/dart-lang/linter/blob/e97275dfa6076686233931d6586544beb8b7ac27/tool/travis.sh#L34

(The output is not great.)

The smoking gun for your build is this bit:

```
  "suggestions": [
   {
    "code": "pubspec.dependencies.outdated",
    "level": "warning",
    "title": "Support latest dependencies.",
    "description": "The version constraint in `pubspec.yaml` does not support the latest published versions for 1 dependency (`analyzer`).",
    "score": 10.0
   }
  ]
 },

```

**Comment by pq** [comment]
OK, so this comes down to a new available `analyzer` package; unfortunately, there does not appear to be a compatible `dart_style` package available so we're stuck at the moment.

The good news that the travis infrastructure issues seem fixed so at least I can see the failed build!

I'll go ahead and merge and pickup the dependency issue separately.

Thanks for the contribution!

**Comment by tenhobi** [comment]
OK, thanks. :-)

**Comment by tenhobi** [comment]
@pq I will ask here, since this PR was merged a while ago.

Should I, and can I, make badges to the linter web page as well as flutter and pedantic does? (http://dart-lang.github.io/linter/lints/)

I think that would be cool feature.

**Comment by pq** [comment]
Great idea @tenhobi!

**Comment by tenhobi** [comment]
I will make separate PR tomorrow, thanks! 💙

**Comment by pq** [comment]
Super.  Let me know if you hit any snags!

**Pull request merged**
