### PR TITLE
analyzer 1.4.0

### PR DESCRIPTION
**Pull request by pq**
/cc @bwilkerson

### CODE REVIEW

**Comment by pq** [comment]
Ah.  This is interesting.  The `unsafe_html` lint tests are failing w/ this bump.

/fyi @srawlins @scheglov

**Comment by pq** [comment]
Specifically, this:

```dart
(C() as dynamic).src = 'foo.js'; // LINT
```

is no longer linting.

🤔

**Comment by pq** [comment]
Hrmmm...

It looks like we're not linting here:

```dart
  // As a SecurityLintCode, unsafe_html reports cannot be ignored.
  // ignore: unsafe_html
  IFrameElement()..srcdoc = 'foo'; // LINT
```

Did something change wrt to `SecurityLintCode`s?

**Comment by pq** [comment]
> Did something change wrt to SecurityLintCodes?

Chatting w/ @srawlins, the answer is yes.  Updating test.

**Comment by pq** [comment]
Hrmmm pt 2.  Formatting churn is interesting.  `dart format` is silent locally but I'm building a fresh SDK and will try again.

**Review by bwilkerson — APPROVED** [review]

**Pull request merged**
