### PR TITLE
Generate docs and push to gh-pages automatically

### LINKED ISSUE #1207: consider publishing docs to gh-pages as a build step

### PR DESCRIPTION
**Pull request by parlough**
Automatically generates HTML docs and pushes to gh-pages. This will allow updates to lint documentation (and lints json) to be updated quicker as well as reduce steps required during a linter release. 

I also adjusted the documentation generation tool to optionally only generate HTML and create the necessary directories.

This will result in commits to gh-pages that look like: https://github.com/parlough/linter/commit/e13db3060b1477ff6c4994e0aa08c9cafcb5d505

_Using same deploy action as flutter/sample's similar [deploy workflow](https://github.com/flutter/samples/blob/main/.github/workflows/gh-pages.yml)._

Fixes #1207

### CODE REVIEW

**Comment by kevmoo** [comment]
How much do we care about pushing lints that may not be available in a stable SDK (yet)?

Does the doc generation do a good job of highlighting (or hiding) pre-release lints?

**Comment by parlough** [comment]
We already publish lints not in a stable SDK, as the website is generally updated when a new linter release is made. 

The site currently indicates what linter version the lint is available in and "Unreleased" if not in any linter release yet.

**Comment by pq** [comment]
This looks fantastic.  Thank you!

**Review by pq — APPROVED** [review]
💎

**Pull request merged**
