### PR TITLE
Fix documentation for `omit_local_variable_types`

### PR DESCRIPTION
**Pull request by Rexios80**
# Description

Not sure what was up with the old documentation, but that's definitely not how this lint works in its current state

### CODE REVIEW

**Comment by parlough** [comment]
We use this syntax to highlight specific code in analyzer diagnostics, but we don't support it for linter rules anywhere, so removing this makes sense for now. Nice catch :)

**Review by bwilkerson — APPROVED** [review]

**Review by pq — APPROVED** [review]

**Comment by pq** [comment]
Thanks!

**Comment by Rexios80** [comment]
Is seems like the action to deploy this change failed for some reason: https://github.com/dart-lang/linter/actions/runs/3963114079

Should it be re-ran?

**Comment by pq** [comment]
Thanks.  It was a transient error and seems to have cleared itself up.

**Pull request merged**
