### PR TITLE
Tests validating implicit const handling (#910).

### PR DESCRIPTION
**Pull request by pq**
See: #910.

### CODE REVIEW

**Comment by pq** [comment]
cc @a14n

**Comment by a14n** [comment]
Thanks

**Comment by a14n** [comment]
Should we change the `environment/sdk` constraint in `pubspec.yaml` ? Not sure that we support all the versions.

**Comment by a14n** [comment]
Linter depends on analyzer `^0.31.2-alpha.0` and analyzer-0.31.2-alpha.0 needs a sdk `>=2.0.0-dev` so it looks like we could update the `environment/sdk` of linter to have the same sdk constraint.

**Pull request merged**
