### PR TITLE
update always_specify_types to lint generic methods

### LINKED ISSUE #1138: Add a lint to require types on generic methods
Right now, there's no lint that catches (e.g.) the lack of a type argument on the `Iterable.map` method.
It would be nice to be able to know where we're missing them.
Also, ideally such a lint would not trigger if the method in question is labeled with `@optionalTypeArgs`.

cc @a14n

### PR DESCRIPTION
**Pull request by a14n**
Fixes #1138

### CODE REVIEW

**Comment by bwilkerson** [comment]
I'm concerned about the number of false positives. You're correct that the SDK cannot reference anything outside the SDK, making it impossible (currently) to mark generic methods in the SDK as having optional type parameters.

One possibility is to split this rule into three parts:
- requiring type annotations (like for variables, etc.),
- requiring type arguments for classes, and
- requiring type arguments for methods.

That would at least keep a change like this from breaking existing users of the lint who don't want to go quite as far as to add type arguments to all method invocations.

**Comment by a14n** [comment]
>One possibility is to split this rule into three parts

+1

**Comment by a14n** [comment]
Split done in #1153

**Comment by a14n** [comment]
As of https://github.com/dart-lang/linter/pull/1153#issuecomment-420429379 I will re-open this one and maintain the 2 branchs

**Comment by a14n** [comment]
hmm, I can't reopen :-/ I created #1178

**Pull request closed without merging**
