### PR TITLE
Check unrelated types on cascades

### PR DESCRIPTION
**Pull request by srawlins**
# Description

Cascades were not checked by `list_remove_unrelated_type` or `iterable_contains_unrelated_type`. This fixes that.

Fixes https://github.com/dart-lang/linter/issues/3698

### CODE REVIEW

**Review by bwilkerson — APPROVED** [review]

**Comment by pq** [comment]
Nice.

This will need some testing against Flutter and Google3 but any fixes will be welcome I'm sure!

**Review by pq — APPROVED** [review]
💎

**Comment by srawlins** [comment]
Looks good on FLutter and Google smoke test

**Comment by pq** [comment]
Cool!  I see flutter-analyze here: https://dart-review.googlesource.com/c/sdk/+/259508.  Did you try a global presubmit internally?

**Comment by srawlins** [comment]
Two breakages on a TGP; I'll clean up first.

**Comment by pq** [comment]
Sweet, thanks!

**Comment by srawlins** [comment]
TGP is now clean.

**Pull request merged**
