### PR TITLE
write and verify `rules.json`

### LINKED ISSUE #4587: Preserve machine-generated linter rules JSON file
The machine-generated `rules.json` file found on the `gh-pages` branch at https://github.com/dart-lang/linter/blob/gh-pages/lints/machine/rules.json is still used by a few clients. 

For the purposes of moving to the SDK, it should potentially be checked in to the `main` branch with a test to make sure it's up to date.

\cc @pq

### PR DESCRIPTION
**Pull request by pq**
Fixes #4587

@parlough: let me know if this is what you had in mind?

/cc @bwilkerson @srawlins

### CODE REVIEW

**Comment by parlough** [comment]
I'm generally happy with this, but it may not be what you want, since it will break if one of the `lints` packages modifies their list of lints or the error fix status map changes. Perhaps we want to adjust those to the latest stable tag/commit rather than `main`?

**Comment by pq** [comment]
Great points!

My gut is that in practice we won't get bitten here too often. My thinking being:

1. `lints` and `flutter_lints` updates happen very infrequently, and while
2. `error_fix_status.yaml` might change more frequently, it will become less of a hassle when we're co-located in the same repo and can make atomic changes

I guess I'm inclined to take the "simple" approach first and rethink if it becomes a problem down the road.

How does that sound?

**Comment by parlough** [comment]
Sounds good to me :)

**Comment by pq** [comment]
> Another benefit of that is it more closely matches what most users will experience.

Regarding this, won't the version of `rules.json` users generally interact w/ still be on `dart.dev` somewhere? And correspond to the latest stable release?

**Comment by parlough** [comment]
> Regarding this, won't the version of rules.json users generally interact w/ still be on dart.dev somewhere? And correspond to the latest stable release?

It's kind of in an awkward spot for now. Since the analyzer still points to the the linter rule documentation rather than the diagnostic version for lints, I try to keep it up to date for `main`. That way new lints don't have a dead link for users on `beta` and `dev`. So for now I have just been manually updating the fix status to match stable.

**Review by bwilkerson — APPROVED** [review]

**Pull request merged**
