### PR TITLE
fix issue in const error handling

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
>

It looks like some errors can not be used to create `AnalysisError`. For instance analyzer shows no error for `new AnalysisError(null, null, null, CompileTimeErrorCode.AMBIGUOUS_EXPORT)` but fails at runtime with `--enable-asserts`.

**Comment by pq** [comment]
@a14n: should I push out a new release w/ this fix?

**Comment by a14n** [comment]
@pq go for a new release (dart-lang/sdk#33647 been related to analyzer it shouldn't impact linter)

**Comment by pq** [comment]
Will do.  Thanks!

**Comment by bwilkerson** [comment]
> ... analyzer shows no error for new AnalysisError(null, null, null, CompileTimeErrorCode.AMBIGUOUS_EXPORT) but fails at runtime with --enable-asserts.

The messaging is poor, but that happens when the error expects arguments and none are provided.

**Pull request merged**
