### PR TITLE
target `dev`

### LINKED ISSUE #2322: re-target `dev` for builds
The `2.12.0-0.0.dev` build appears to have a fix for https://github.com/dart-lang/sdk/issues/43979 but has another snag.

image

See #2319 .

**UPDATE:** SDK issue tracked in https://github.com/dart-lang/sdk/issues/44027.

### PR DESCRIPTION
**Pull request by pq**
Fixes #2322 

(EDIT: looks like this is ready to go.)

/cc @devoncarew @bwilkerson

### CODE REVIEW

**Comment by pq** [comment]
fyi @devoncarew: I thought `dev` should be good with the `dartdev` fix but apparently not?

**Comment by devoncarew** [comment]
> fyi @devoncarew: I thought `dev` should be good with the `dartdev` fix but apparently not?

I don't believe we've release a new dev yet -

**Comment by devoncarew** [comment]
> I don't believe we've release a new dev yet -

Oh, perhaps this morning? It's worth a try.

**Comment by pq** [comment]
yeah. A new dev release is out but it doesn't include the fix.

image


we'll have to wait for the next one...

**Comment by devoncarew** [comment]
Is that the same exception?

**Comment by pq** [comment]
Oh dear.  It looks like not.

/cc @bkonyi

**Review by devoncarew — APPROVED** [review]

**Pull request merged**
