### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Is nice!

**Comment by bwilkerson** [comment]
Phil is out this week. What does this bot do?

**Comment by kevmoo** [comment]
@bwilkerson – makes sure our actions are using the latest dependencies.

**Review by bwilkerson — APPROVED** [review]
Sounds like a reasonable thing to check.

**Review by pq — COMMENTED** [review]
👍

**Pull request merged**
