### PR TITLE
Enable `unnecessary_final`

### PR DESCRIPTION
**Pull request by pq**
As per the updated advice in "Effective Dart": https://dart.dev/guides/language/effective-dart/usage#do-follow-a-consistent-rule-for-var-and-final-on-local-variables, this enforces an opinion on `var` over `final` for locals.

/cc @bwilkerson

### CODE REVIEW

**Comment by parlough** [comment]
I'm curious what the rationale for going this direction is. I personally find using `final` helps makes code easier to understand as readers know it won't be reassigned, and also prevents users from doing so accidentally. 

I'm happy to standardize on whatever is decided, just curious.

**Comment by pq** [comment]
Thanks for chiming in!  I have some personal feelings about this one (and actually argued for `final` for a long time) but feel that its merits are sort of negligible/tenuous in practice and would prefer standardization (who's benefits are more easily measured).  If you look at the SDK, while consistency is not enforced, there is a tendency towards `var` and so I'd like to just bite the bullet and get on board.  (FWIW: the current mixed standard *is* distracting to me personally so if we didn't turn this on, I'd want to turn on `prefer_final_locals` but that feels like we're swimming away from a kind of growing standard in the SDK and I just don't see the benefit.)

**Comment by pq** [comment]
> I personally find using final helps makes code easier to understand as readers know it won't be reassigned, and also prevents users from doing so accidentally.

Anecdotally, I thought this was true for me too until I spent a bunch of time in a codebase that didn't use `final` for locals and frankly never missed them.   Obviously that's just me though!

**Comment by parlough** [comment]
@pq Thanks for the extra context. I agree the mix is distracting, so I'm glad the linter is standardizing on something. 

I think the reasoning seems fair and like you said it seems common for people to gravitate towards `var` already. 

I'm happy to adapt towards a standard but it'll take changing some muscle memory ;) 

https://dart-review.googlesource.com/c/sdk/+/192720 will help - thanks!

**Comment by pq** [comment]
I hear you about muscle memory.  That's big for me too.  I realize this is a bit of a change and may be jarring.  The good news is that if we decide we don't like it, we can go back.  If there isn't a comparable set of fixes for `prefer_final_locals`, we can add em!

> https://dart-review.googlesource.com/c/sdk/+/192720 will help - thanks!

Entirely the motivation.  Much easier when you can just run `dart fix`!

**Review by parlough — APPROVED** [review]

**Review by bwilkerson — APPROVED** [review]

**Pull request merged**
