### PR TITLE
badge core and recommended

### PR DESCRIPTION
**Pull request by pq**
Fixes: https://github.com/dart-lang/linter/issues/2624

image

image

(EDIT: swapped colors.)

Badges could be made tidier (I just used the generator in shields.io).  Maybe @parlough has ideas for that?

/cc @bwilkerson @parlough

### CODE REVIEW

**Comment by parlough** [comment]
I'm no designer and my thinking is that developers are familiar with these shields(?) and can add them to their READMEs if they like. 

A slight nit, but perhaps switch the primary colors of `core` and `recommended`. The darker color of `core` draws me to it and makes it seem like it's the greater of the two, but `recommended` is really the greater of the two.

**Comment by pq** [comment]
> A slight nit, but perhaps switch the primary colors of core and recommended. 

Done. 👍

**Review by bwilkerson — APPROVED** [review]

**Comment by bernaferrari** [comment]
I only saw this now, but don't you think "flutter"s contrast is too low? Core is a lot darker than flutter and got a dark color..

**Comment by pq** [comment]
Darker makes sense.  I made a quick one but don't love the hue.  

@bernaferrari or @parlough: if you want to play with improved colors, I'd be happy to review.

here's what I've been using:

https://shields.io/

and for example,

https://img.shields.io/badge/style-flutter-27357e?style=flat-square

Thanks for the help!

**Comment by pq** [comment]
image

**Comment by bernaferrari** [comment]
I played a bit with this https://components.ai/color-scale using dart colors and came to this suggestion. I liked most the last one (core: #0C71B3, recommended: #014983, flutter: #003056).

color interpolator

**Comment by pq** [comment]
Do you want to open a pull request?  (They'll need to be SVGs.)

https://github.com/dart-lang/linter/tree/gh-pages

**Comment by bernaferrari** [comment]
Yes, but can you help me find them in the codebase? I can see `style-flutter.svg` reference in doc.dart, but there is no file, no img.shields.io reference. It looks like magic.

**Comment by pq** [comment]
Of course!

The trick is to be on the gh-pages branch:

https://github.com/dart-lang/linter/tree/gh-pages/lints

**Comment by bernaferrari** [comment]
When I forked it went from gh to master 😅 thanks!

**Comment by pq** [comment]
No problem.  Thanks so much for the contribution!

**Pull request merged**
