### PR TITLE
New rule for AngularDart2 : Specify template or templateUrl but not both when annotating with @Component.

### PR DESCRIPTION
**Pull request by alexeieleusis**
Sending PR since `git cl upload` stopped working.
@pq @bwilkerson 

previous patches were reviewed at https://codereview.chromium.org/2402943002

### CODE REVIEW

**Comment by bwilkerson** [comment]
I think having angular-specific lints is great, but I don't think the linter package is the right place for this. I have serious concerns about adding a dependency from the linter package to angular2.

Have you talked to the reviewer I added to the previous CL about a different home for this code?

**Comment by alexeieleusis** [comment]
cc @vikerman

**Comment by pq** [comment]
I agree with @bwilkerson that we want to be careful about where these lints go. Adding a dependency on angular to the linter and so by extension onto the Dart SDK which is a show-stopper.

Unfortunately, we really don't (despite lots of effort) have a proper dynamic plugin story for Dart and so things like this are just hard in the general case.  On the bright side, as Brian pointed out, there is a bunch of work going on to solve this problem specifically for angular so there may be hope yet.  @vikerman I expect will have ideas.

**Comment by vikerman** [comment]
Hey - I am resurrecting https://github.com/angular/angular2-dart-analyzer - Updating it for current angular2 library and templates. It would surface errors in the templates in Dart and HTML files, that would be immediately available in the IDE. We are not ready for soft errors/warnings like this particular issue yet and maybe we need a separate Angular 2 linter later - Please file an issue in the other repo and we can track it.

**Comment by pq** [comment]
@alexeieleusis: Can we close this one?

**Comment by bwilkerson** [comment]
This should be part of the angular plugin.

**Comment by alexeieleusis** [comment]
ditto, I will eventually ping the angular team to move this to that plugin.

**Pull request closed without merging**
