### PR TITLE
Fixing a bug where GitHub usernames starting with a digit where not accepted

### LINKED ISSUE #3331: Flutter_Style_Todo not allowing GitHub usernames starting with digits
**Describe the issue**
The regex does not accept Github usernames starting with digits.
// TODO(myname): would work
// TODO(1nf0rmatix): would not

**To Reproduce**
// TODO(myname): would work
// TODO(1nf0rmatix): would not

**Expected behavior**
// TODO(1nf0rmatix): Blabla should be valid

### PR DESCRIPTION
**Pull request by 1nf0rmatix**
# Description

The regex did not accept Github usernames starting with digits.
// TODO(myname): would work
// TODO(1nf0rmatix): would not

Fixes #3331

### CODE REVIEW

**Comment by pq** [comment]
Thanks for the contribution!

Could you fill out a CLA?  

For more information, open the [CLA check for this PR](https://github.com/dart-lang/linter/pull/3332/checks?check_run_id=5833809608).

**Comment by pq** [comment]
Also, @1nf0rmatix: could you add an attribution to `AUTHORS`?

**Comment by 1nf0rmatix** [comment]
I already did???

Mit besten Grüßen

Paul Köhler

Am 05.04.2022 um 19:59 schrieb Coveralls ***@***.***>:

﻿

[Coverage Status]<https://coveralls.io/builds/48021534>

Coverage remained the same at 95.634% when pulling 84bdffd<https://github.com/dart-lang/linter/commit/84bdffd8579901c06ab907c6c24006f9290823df> on 1nf0rmatix:patch-1 into bd3c12b<https://github.com/dart-lang/linter/commit/bd3c12b8aaa68b1fa95f2dfcdf0094ff3b10d0c2> on dart-lang:master.

**Comment by 1nf0rmatix** [comment]
Will do tomorrow :)

Am 05.04.2022 um 19:57 schrieb Phil Quitslund ***@***.***>:

﻿

Also, @1nf0rmatix<https://github.com/1nf0rmatix>: could you add an attribution to AUTHORS?

**Review by bwilkerson — APPROVED** [review]

**Comment by 1nf0rmatix** [comment]
@bwilkerson please review and merge :)

**Comment by 1nf0rmatix** [comment]
> Also, @1nf0rmatix: could you add an attribution to `AUTHORS`?

Done @pq

**Review by pq — APPROVED** [review]
Thank you!

**Pull request merged**
