### PR TITLE
Remove invocations of registerDefault method since it no longer exists.

### PR DESCRIPTION
**Pull request by alexeieleusis**

### CODE REVIEW

**Comment by bwilkerson** [comment]
I don't understand this change. The method `Registry.registerDefault` is defined in `sdk/pkg/analyzer/lib/src/lint/registry.dart`. What do you mean by "it no longer exists"?

**Comment by alexeieleusis** [comment]
When I ran the linter locally it was crashing and when in intellij it had res wiggles saying the method does not exist.

Will verify.

**Comment by bwilkerson** [comment]
Is it loaded with / compiled against bleeding edge analyzer? That's the only combination that works at the moment.

**Comment by alexeieleusis** [comment]
Discarded, both intellij and command line run flawless without this change now.

**Pull request closed without merging**
