### PR TITLE
WIP: avoid_future_catcherror rule

### PR DESCRIPTION
**Pull request by christopherfujino**
TODO description

### CODE REVIEW

**Comment by srawlins** [comment]
Quick drive by as this would require a lot of rename work: We typically convert camelCase to snake_case, like in `avoid_type_to_string` or `no_logic_in_create_state` (ignore `avoid_function_literals_in_foreach_calls` and `no_runtimeType_toString`! 🤣  ).

**Comment by christopherfujino** [comment]
> Quick drive by as this would require a lot of rename work: We typically convert camelCase to snake_case, like in `avoid_type_to_string` or `no_logic_in_create_state` (ignore `avoid_function_literals_in_foreach_calls` and `no_runtimeType_toString`! rofl ).

so s/avoid_future_catcherror/avoid_future_catch_error, or other updates too?

**Comment by srawlins** [comment]
Oh, also, we I think are trying to avoid the word `avoid`. @pq would this be just `future_catch_error`?

In any case, you don't have to put more work into this until we settle on what kind of lint rule we want.

**Comment by christopherfujino** [comment]
> Oh, also, we I think are trying to avoid the word `avoid`. @pq would this be just `future_catch_error`?
> 
> In any case, you don't have to put more work into this until we settle on what kind of lint rule we want.

ack on both points.

**Comment by devoncarew** [comment]
Thanks for the contribution! The code for the linter has since moved into the sdk repo (at https://github.com/dart-lang/sdk/tree/main/pkg/linter). If you think this PR is still relevant, consider re-creating it against the source there (see https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md).

**Pull request closed without merging**
