### PR TITLE
widen application of prefer_null_aware_operators

### PR DESCRIPTION
**Pull request by a14n**
Remove restriction on `prefer_null_aware_operators` (was only applied for local variables).

### CODE REVIEW

**Comment by a14n** [comment]
Tested on Flutter I haven't seen false positives.

**Comment by bwilkerson** [comment]
Sorry for the delay. Most of the Dart team is at an off-site this week.

Interested to know how many cases it found, and the nature of those cases (for example, what percentage of the cases were references to parameters, for example).

I have no concerns with widening the lint to flag parameters, but, while the probability of finding code like this is small, any code that includes a getter or a method invocation could potentially have side effects such that the suggested transformation would change the semantics. I'll wait for @pq to weigh in on whether it's worth the risk of false positives.

Also, does our quick fix / assist for this case need to be updated?

**Comment by a14n** [comment]
>Interested to know how many cases it found, and the nature of those cases (for example, what percentage of the cases were references to parameters, for example).

There are only 3 lints for this update. You can find them in flutter/flutter#32711

**Comment by pq** [comment]
@a14n: reading https://github.com/flutter/flutter/pull/32711#issuecomment-492930932, are you dropping this?

**Comment by a14n** [comment]
Yes and no :smile:

This linter PR is still valid and should be merged (actually https://github.com/dart-lang/linter/pull/1567#issuecomment-492650767 and https://github.com/dart-lang/linter/pull/1567#issuecomment-492825814 should have been done on this PR).

The rollback I made on flutter is to avoid changing the current behaviour. I will revisit flutter with this lint once NNBD has landed. That said with this lint PR the next linter roll in flutter will need to comment out `prefer_null_aware_operators` in analysis_options.yaml.

**Comment by pq** [comment]
Ah.  Thanks for the clarification!

>> That said with this lint PR the next linter roll in flutter will need to comment out prefer_null_aware_operators in analysis_options.yaml.

Would you mind updating Flutter before this lands?  I'm hoping to publish and integrate as early as tomorrow and this would break the `flutter-analyze-try` bot blocking a land in the SDK.

**Comment by a14n** [comment]
I updated flutter/flutter#32711 to disable `prefer_null_aware_operators`

**Comment by a14n** [comment]
@pq flutter/flutter#32711 is now merged

**Comment by pq** [comment]
Super.  Thanks for the prompt follow-through!

**Pull request merged**
