### PR TITLE
Update misc testing documentation

### PR DESCRIPTION
**Pull request by parlough**
Switches test run instructions from `pub run test` to simply `dart test`.

### CODE REVIEW

**Comment by pq** [comment]
This is a little tricky.  Since the linter source is used internally at Google (and possibly elsewhere) for testing, changes like this are breaking and need to be carefully considered.  Consider opening an issue proposing the change so we can pickup (and promote) conversation there?

Thanks!

**Comment by parlough** [comment]
@pq Thanks for pointing that out, I didn't fully consider that. I've gone ahead and undid the removal of the test util so the `pub run test -> dart test` updates can still be merged if desired. 

After some more testing, there seems to still be some issues with VM debugging anyway that I will investigate more and followup with an issue to discuss.

**Comment by parlough** [comment]
Will revisit this in the future.

**Comment by pq** [comment]
Thanks a million @parlough!  (And sorry for the slow resolution on  things generally.  Should speed up once we square away a nullability release...)

**Pull request closed without merging**
