### PR TITLE
Update badge colors.

### PR DESCRIPTION
**Pull request by bernaferrari**
image

Question: should effective_dart become gray with pedantic? Or we keep it as is for now?

https://github.com/dart-lang/linter/pull/2717

### CODE REVIEW

**Comment by pq** [comment]
This is fantastic.  Thank you!

> Question: should effective_dart become gray with pedantic? Or we keep it as is for now?

I think **yes**.

**Comment by pq** [comment]
@bernaferrari : what's a good attribution for you?  I'd like to add you to [AUTHORS](https://github.com/dart-lang/linter/blob/master/AUTHORS).

**Review by pq — APPROVED** [review]
💎

**Comment by bernaferrari** [comment]
Oh! That's awesome, I'm flattered 😂

Bernardo Ferrari <bernaferrari2@gmail.com>

**Comment by pq** [comment]
Thanks again @bernaferrari!

**Pull request merged**
