### PR TITLE
Revert "Revert "unreachable_from_main: Report unreachable constructors (#4162)" (#4253)"

### PR DESCRIPTION
**Pull request by srawlins**
This reverts commit b56190503725de2125b626ff1b3423192fa1f7ae.

Also: Add support for test_reflective_loader

### CODE REVIEW

**Comment by srawlins** [comment]
This is still ready for review.

**Review by bwilkerson — APPROVED** [review]
Is this the same as the original PR? If so, lgtm. If not, I'll be happy to do a more careful review.

**Comment by srawlins** [comment]
As the description notes, it is mostly a revert, plus a small fix for 'test_reflective_loader'. I think if you CTRL+F for test_reflective_loader in the diff, you can get a good handle on what is new. That new code is small relative to the reverted diff.

**Review by bwilkerson — APPROVED** [review]
That diff lgtm.

**Pull request merged**
