### PR TITLE
Report type_literal_in_constant_pattern more often.

### PR DESCRIPTION
**Pull request by scheglov**
As requested in https://github.com/dart-lang/linter/issues/4195#issuecomment-1523954808

### CODE REVIEW

**Review by pq — APPROVED** [review]
🎉

**Review by bwilkerson — APPROVED** [review]

**Comment by mit-mit** [comment]
Is this something we might be able to cherry pick?

**Comment by scheglov** [comment]
The past experience left me with a feeling that we don't to cherry picks for linter.
@pq might confirm, or claim that I'm exaggerating :-)

**Comment by bwilkerson** [comment]
We are able to do cherry picks from the linter, but it requires creating a new linter branch based on the last branch pulled into the SDK, applying the changes on that branch, and then pulling the new branch into the target SDK branch (bypassing the main SDK branch).

**Comment by pq** [comment]
Yep. What Brian said. The most careful way to cherry-pick a linter fix is a bit painful and time-consuming. Alternatively we could pull in more changes and shoulder a bit of risk.

If this is high priority, I'm happy to look into it.

**Comment by mit-mit** [comment]
We discussed this in the language team, and we think that it's high value enough to pursue as a cherry pick. We'll let you folks decide if the best approach is a linter roll or just patching this single change in.

**Comment by mit-mit** [comment]
@pq did you have a chance to look into a cherry pick?

**Comment by pq** [comment]
Yeah. I'm working on it. The trick is we'd like to get the change landed into main first so that the cherry-pick isn't out of sync with what's at tip of tree. That roll has been stalled for other reasons (https://dart-review.googlesource.com/c/sdk/+/304360) but we're getting there!

**Pull request merged**
